domains_to_block:
  - twitter.com
  - www.twitter.com
  - instagram.com
  - www.instagram.com
  - api.twitter.com
  - x.com
  - www.x.com
  - api.x.com
  - youtube.com
  - www.youtube.com
  - studio.youtube.com
  - whatsapp.com
  - web.whatsapp.com
  - gmail.com
  - www.gmail.com
  - app.convertkit.com
  - slack.com
  - discord.com

bookmarks_api_url: "https://bookmarks.alexvyber.dev/bookmarks"

repos:
- "dotfiles"

- "@alexvyber/_repos/1000days-cli"
- "@alexvyber/_repos/1000DaysOfCode"
- "@alexvyber/_repos/alexvyber"
- "@alexvyber/_repos/blank"
- "@alexvyber/_repos/boring"
- "@alexvyber/_repos/classic"
- "@alexvyber/_repos/cvax"
- "@alexvyber/_repos/dazzleui"
- "@alexvyber/_repos/doingstuff"
- "@alexvyber/_repos/electro"
- "@alexvyber/_repos/genstuff"
- "@alexvyber/_repos/katzen-csv"
- "@alexvyber/_repos/learn"
- "@alexvyber/_repos/math-not-meth"
- "@alexvyber/_repos/neovim"
- "@alexvyber/_repos/one-billion-checkbox"
- "@alexvyber/_repos/presentor"
- "@alexvyber/_repos/pushstuff"
- "@alexvyber/_repos/shmoodle-meet"
- "@alexvyber/_repos/mothman"
- "@alexvyber/_repos/StupidImageUploader"
- "@alexvyber/_repos/StupidTimer"
- "@alexvyber/_repos/stw"
- "@alexvyber/_repos/turbo-helpers"
- "@alexvyber/_repos/type-challenges"
- "@alexvyber/_repos/vyber-cli"
- "@alexvyber/_repos/vybzen"

### REPOS ###
- "REPOS/node"
- "REPOS/fastify"
- "REPOS/TypeScript"
- "REPOS/DefinitelyTyped"
- "REPOS/pino"
- "REPOS/v8"
- "REPOS/zustand"
- "REPOS/vite"
- "REPOS/strapi"
- "REPOS/react"
- "REPOS/eslint"
- "REPOS/fastify"
- "REPOS/fastify-vite"
- "REPOS/headlessui"
- "REPOS/jotai"
- "REPOS/knex"
- "REPOS/ky"
- "REPOS/ladle"
- "REPOS/nativewind"
- "REPOS/next.js"
- "REPOS/nextra"
- "REPOS/node"
- "REPOS/openapi-typescript"
- "REPOS/pino"
- "REPOS/prettier-plugin-tailwindcss"
- "REPOS/react-pdf"
- "REPOS/react-sortablejs"
- "REPOS/remeda"
- "REPOS/sonner"
- "REPOS/sort-package-json"
- "REPOS/sql-ts"
- "REPOS/strapi"
- "REPOS/stylex"
- "REPOS/ts-reset"
- "REPOS/TypeScript"
- "REPOS/typescript-eslint"
- "REPOS/TypeStat"
- "REPOS/undici"
- "REPOS/uploadthing"
- "REPOS/v"
- "REPOS/v8"
- "REPOS/vite"
- "REPOS/vite-plugin-stylex"
- "REPOS/zustand"


### WORK ###
- "work/nd/root"


# drivingbees
- "work/drivingbees/api"
- "work/drivingbees/cms"
- "work/drivingbees/marketing"
- "work/drivingbees/mobile"
- "work/drivingbees/changelog"
- "work/drivingbees/design-system"
- "work/drivingbees/web"
- "work/drivingbees/docs"

autocommit_repos:
- "dotfiles"

# drivingbees
- "work/drivingbees/api"
- "work/drivingbees/cms"
- "work/drivingbees/marketing"
- "work/drivingbees/mobile"
- "work/drivingbees/changelog"
- "work/drivingbees/design-system"
- "work/drivingbees/web"
- "work/drivingbees/docs"

- "@alexvyber/_repos/vyber-cli"
- "@alexvyber/_repos/1000days-cli"
- "@alexvyber/_repos/1000DaysOfCode"
- "@alexvyber/_repos/alexvyber"
- "@alexvyber/_repos/blank"
- "@alexvyber/_repos/boring"
- "@alexvyber/_repos/classic"
- "@alexvyber/_repos/cvax"
- "@alexvyber/_repos/dazzleui"
- "@alexvyber/_repos/doingstuff"
- "@alexvyber/_repos/electro"
- "@alexvyber/_repos/genstuff"
- "@alexvyber/_repos/katzen-csv"
- "@alexvyber/_repos/learn"
- "@alexvyber/_repos/math-not-meth"
- "@alexvyber/_repos/neovim"
- "@alexvyber/_repos/one-billion-checkbox"
- "@alexvyber/_repos/presentor"
- "@alexvyber/_repos/pushstuff"
- "@alexvyber/_repos/shmoodle-meet"
- "@alexvyber/_repos/mothman"
- "@alexvyber/_repos/StupidImageUploader"
- "@alexvyber/_repos/StupidTimer"
- "@alexvyber/_repos/stw"
- "@alexvyber/_repos/turbo-helpers"
- "@alexvyber/_repos/type-challenges"
- "@alexvyber/_repos/vyber-cli"
- "@alexvyber/_repos/vybzen"























