session_name: app
windows:
- layout: tiled
  shell_command_before:
  - cd /home/alexs/elixir/learn/programming_ecto/working/app
  window_name: root
- layout: tiled
  shell_command_before:
  - cd /home/alexs/elixir/learn/programming_ecto/working/app/lib/app
  window_name: model
- layout: tiled
  shell_command_before:
  - cd /home/alexs/elixir/learn/programming_ecto/working/app/lib/app_web/
  window_name: web
- layout: tiled
  shell_command_before:
  - cd /home/alexs/elixir/learn/programming_ecto/working/app
  - l
  window_name: run
- layout: tiled
  shell_command_before:
  - cd /home/alexs/elixir/learn/programming_ecto/working/app/priv/
  window_name: priv
- layout: tiled
  shell_command_before:
  - cd /home/alexs/elixir/learn/programming_ecto/working/app/lib/app_web/live
  window_name: live
- layout: tiled
  shell_command_before:
  - cd /home/alexs/elixir/learn/programming_ecto/working/app/config/
  window_name: config
- layout: tiled
  shell_command_before:
  - cd /home/alexs/elixir/learn/programming_ecto/working/app/assets/
  window_name: assets
- layout: tiled
  shell_command_before:
  - cd /home/alexs/elixir/learn/programming_ecto/working/app/lib/app_web/templates
  window_name: templates
- layout: tiled
  shell_command_before:
  - cd /home/alexs/elixir/learn/programming_ecto/working/app/test/
  window_name: test
